# Overseerr services.yaml entries
submit_movie_request:
  description: Searches for a movie and requests the first result.
  fields:
    name:
      description: Search parameter
      example: "beverly hills cop"

submit_tv_request:
  description: Searches for a TV show and requests the first result.
  fields:
    name:
      description: Search parameter
      example: "breaking bad"
    season:
      description: Which season(s) to request (first, latest or all)
      example: "latest"

submit_music_request:
  description: Searches for a music album and requests the first result.
  fields:
    name:
      description: Search parameter
      example: "nevermind"

update_request:
  description: Updates the status of specified request to pending/approve/decline/available
  fields:
    request_id:
      description: ID of the request to update
      example: 30
    status:
      description: New Status (can be pending/approve/decline/available)
      example: "approve"
